backend = "resized"
threshold = 10
palette = "dark"

[templates]
kitty.template = 'kitty-colors.conf'
kitty.target = '~/.config/kitty/colors-wallust.conf'
waybar.template = 'waybar-colors.css'
waybar.target = '~/.config/waybar/colors-wallust.css'
